version: '3'

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=server
    environment:
      - ADDRESS=0.0.0.0
      - METARANK_URL=${METARANK_URL}
      - MODEL_NAME=${MODEL_NAME}
    ports:
      - '3001:3001'
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=frontend
    ports:
      - '3000:3000'