version: '3'

services:
  metarank:
    container_name: metarank
    image: metarank/metarank:latest
    command: ["standalone", "--config", "/opt/metarank/config.yml", "--data", "/opt/metarank/events.jsonl.gz"]
    ports:
      - 8080:8080
    volumes:
      - ./metarank:/opt/metarank
    networks:
      - metarank
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=server
    environment:
      - ADDRESS=0.0.0.0
      - METARANK_URL=http://metarank:8080
      - MODEL_NAME=xgboost
    ports:
      - '3001:3001'
    networks:
      - metarank
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_CONTEXT=frontend
    ports:
      - '3000:3000'
    networks:
      - metarank
networks:
  metarank:
    driver: bridge
